[metadata]
name = abks-sniffer
version = 0.1.0
description = Educational cross-platform sniffer and sniffer detector for Linux and Windows
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find:
python_requires = >=3.9
include_package_data = false

[options.packages.find]
where = .
include = sniffer_lab*

[options.entry_points]
console_scripts =
    abks-sniffer = sniffer_lab.cli:main
